name: build debian
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - debian/**
jobs:
  push:
    name: "yolks:${{ matrix.type }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type:
          - minecraft_bedrock
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Copy entrypoint.sh
        run: |
          rm -f ./debian/entrypoint.sh
          cp ./debian/${{ matrix.type }}/entrypoint.sh ./debian/entrypoint.sh
      - uses: docker/build-push-action@v2
        with:
          context: ./debian
          file: ./debian/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/alaister-net/yolks:${{ matrix.type }}
