name: build java
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - java/**
jobs:
  push:
    name: "yolks:${{ matrix.type }}_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type:
          - java
          - minecraft_java
          - minecraft_proxy
        tag:
          - 8
          - 11
          - 16
          - 17
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Copy entrypoint.sh
        run: |
          rm -f ./java/entrypoint.sh
          cp ./java/${{ matrix.type }}/entrypoint.sh ./java/entrypoint.sh
      - uses: docker/build-push-action@v2
        with:
          context: ./java
          file: ./java/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/alaister-net/yolks:${{ matrix.type }}_${{ matrix.tag }}
